### ISSUE TITLE
[SC] StartService FALHA 577

### ISSUE THREAD

**Issue by isvktt** [UrAvgCoder/ring0-csg0#3]
The following message appears when loading the driver ''Windows cannot verify the digital signature of this file. Perhaps a recent hardware or software change installed a file with an incorrect or damaged signature, or perhaps the file is malicious software of unknown origin.'' How do I resolve this?

**Comment by UrAvgCoder** [comment]
Hey, I believe you are loading the driver using windows driver load AKA SC.. which cannot be done if you are using a self-built-non-certified driver, which is most probably the case since you must have taken the driver from this repo.

You need to find an alternative way of loading the driver in your windows, I would recommend using KDMapper for an example:

https://github.com/TheCruZ/kdmapper

Credits: TheCruZ
